Fix warning about missing function declaration
spin.y: In function ‘ltl_to_string’:
spin.y:1117:9: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
 1117 |         free(ltl_formula);
      |         ^~~~

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>